_target_: src.models.sam_module.SAM3DModuleLinear

sam_model:
  _target_: ultralytics.models.sam.Predictor
  overrides:
    # See the ultralytics.utils.DEFAULT_CFG for the hyperparameters to be overridden
    conf: 0.25
    task: segment
    mode: predict
    imgsz: 640
    model: ${paths.data_dir}/sam_b.pt

points_stride: 32
points_batch_size: 25
prompt_strategy: grid
