# @package _global_

defaults:
  - _self_
  - data: urn # choose datamodule with `test_dataloader()` for evaluation
  - model: sam
  - logger: mlflow
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: tiff_writing

task_name: "eval"

tags: ["dev"]
# passing checkpoint path is necessary for evaluation
